# Generated by Django 3.2.4 on 2021-06-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redurl', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slugs',
            field=models.ManyToManyField(blank=True, related_name='slugs', to='redurl.RedUrl'),
        ),
    ]
