# Generated by Django 3.2.4 on 2021-06-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('url', models.URLField()),
                ('ip_creator', models.GenericIPAddressField()),
                ('created', models.DateTimeField()),
                ('clicks', models.ManyToManyField(blank=True, related_name='clicks', to='redurl.Click')),
            ],
        ),
    ]
