# Generated by Django 3.2.4 on 2021-06-07 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redurl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redurl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redurl',
            name='user_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(redurl.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='click',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redurl.redurl'),
        ),
        migrations.AddField(
            model_name='click',
            name='user_click',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(redurl.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL),
        ),
    ]
